spring.application.name=user

server.port=9083

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register this service with Eureka
eureka.client.register-with-eureka=true

# Fetch registry from Eureka
eureka.client.fetch-registry=true

# OpenFeign
spring.cloud.openfeign.client.config.default.connect-timeout=2000
spring.cloud.openfeign.client.config.default.read-timeout=3000

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.providerCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.providerCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.providerCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.providerCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.providerCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.providerCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.providerCB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.providerCB.register-health-indicator=true


# Resilience4j Retry
resilience4j.retry.instances.providerRetry.max-attempts=3
resilience4j.retry.instances.providerRetry.wait-duration=500ms
resilience4j.retry.instances.providerRetry.ignore-exceptions=io.github.resilience4j.circuitbreaker.CallNotPermittedException

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents,retries,retryevents