spring.application.name=data-dictionary-service

server.port=8088


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true

django-ai-service.base-url=http://django-ai-service

vision.api.base-url=http://django-ai-service