spring.application.name=BootProj05-ValueAnnotation-ESPL

#Menu price info 

menu.dosarate=50
menu.idlyrate=60
menu.poharate=30
menu.vprate=40


#hotel info

hotel.name=Amoga Hotel
hotel.address=HYD
hotel.contactNo=7666845301

#Customer info
cust.name=Param

