spring.application.name=BootProj06-BulkValuesInjection-ConfigurationPoperties

#animal details

wild.animal.id=101
wild.animal.name=Elephant
wild.animal.jungle=chennai
wild.animal.price=234567.00
wild.animal.food=ghasfuss