spring.application.name=eureka-server
# Eureka server runs on this port - all other services will point here
server.port=8761

# This IS the registry, so it should NOT register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false