spring.application.name=api-gateway
server.port=8099

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[2].id=product-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/products/**

#spring.cloud.gateway.server.webflux.routes[3].id=order-service
#spring.cloud.gateway.server.webflux.routes[3].uri=lb://order-service
#spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/orders/**


jwt.secret=j6rl1ESY5frlRBVS6KNuzAH96P5hA1bWawk5MJw8uko=
jwt.expiration=86400000